site_name:        Unitful.jl
repo_url:         https://github.com/ajkeller34/Unitful.jl
site_description: Performant and expressive calculations with arbitrary units.
site_author:      Andrew J. Keller

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Highlighted features: highlights.md
- Types: types.md
- Defining new units: newunits.md
- Conversion / promotion: conversion.md
- Manipulating units: manipulations.md
- How units are displayed: display.md
- Logarithmic scales: logarithm.md
- Temperature scales: temperature.md
- Extending Unitful: extending.md
- Troubleshooting: trouble.md
- License: LICENSE.md
